# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZnMrbPEaM2N8NG2-ARCQDU5qdxp0kwHG
"""

def add(P,Q):
  return P+Q
def subtract(P,Q):
  return P-Q
def multiply(P,Q):
  return P*Q
def divide(P,Q):
  return P/Q

print("plese select the operation")
print("a.add")
print("b.subtract")
print("c.multiply")
print("d.divide")
choice=input("please enter choice(a/b/c/d):")
num_1=int(input("please enter the first number:"))
num_2=int(input("please enter second number:"))
if choice=='a':
  print(num_1,"+",num_2,"=",add(num_1,num_2))
elif choice=='b':
  print(num_1,"-",num_2,"=",subtract(num_1,num_2))
elif choice=='c':
  print(num_1,"*",num_2,"=",multiply(num_1,num_2))
elif choice=='d':
  print(num_1,"/",num_2,"=",divide(num_1,num_2))
else:
  print("this is an invalid input")

